#ifndef _FIFO_SYMBOLS_H
#define _FIFO_SYMBOLS_H

#define FIFO_CMD_LENGTH 2
#define FIFO_SYMBOL_LENGTH 80

extern const uint8_t FIFO_POLAR_ZERO_FDEV_NEG[FIFO_CMD_LENGTH + FIFO_SYMBOL_LENGTH];
extern const uint8_t FIFO_POLAR_ZERO_FDEV_POS[FIFO_CMD_LENGTH + FIFO_SYMBOL_LENGTH];
extern const uint8_t FIFO_POLAR_ONE[FIFO_CMD_LENGTH + FIFO_SYMBOL_LENGTH];
extern const uint8_t FIFO_POLAR_BEFOREFRAME_1[FIFO_CMD_LENGTH + FIFO_SYMBOL_LENGTH];
extern const uint8_t FIFO_POLAR_BEFOREFRAME_2[FIFO_CMD_LENGTH + 64];
extern const uint8_t FIFO_POLAR_AFTERFRAME_1[FIFO_CMD_LENGTH + FIFO_SYMBOL_LENGTH];
extern const uint8_t FIFO_POLAR_AFTERFRAME_2[FIFO_CMD_LENGTH + FIFO_SYMBOL_LENGTH];

#endif
